name: Headlines
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.5+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #utility
  quiver: ^2.1.3
  url_launcher: ^5.5.0
  hive: ^1.4.4
  path_provider: ^1.6.17

  #bloc pattern
  flutter_bloc: ^5.0.1
  equatable: ^1.2.0

  #api
  dio: ^3.0.9

  #serialization
  built_value: ^7.1.0
  built_collection: ^4.3.2

  #location
  location: ^3.0.2
  geocoding: ^1.0.0
  share: ^0.6.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0 # flutter packages pub run build_runner build
  built_value_generator: ^7.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
